# Generated by Django 3.2.9 on 2021-12-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_auto_20211204_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
    ]
