# Generated by Django 3.2.9 on 2021-12-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0003_auto_20211204_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('slug', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('specification', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carApp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carApp.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carApp.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carApp.size')),
            ],
        ),
    ]
